// This file was auto-generated by Fern from our API Definition.

package client

import (
	automations "github.com/ittybit/sdk-go/automations"
	core "github.com/ittybit/sdk-go/core"
	files "github.com/ittybit/sdk-go/files"
	internal "github.com/ittybit/sdk-go/internal"
	media "github.com/ittybit/sdk-go/media"
	option "github.com/ittybit/sdk-go/option"
	signatures "github.com/ittybit/sdk-go/signatures"
	tasks "github.com/ittybit/sdk-go/tasks"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Automations *automations.Client
	Files       *files.Client
	Media       *media.Client
	Tasks       *tasks.Client
	Signatures  *signatures.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:      options.ToHeader(),
		Automations: automations.NewClient(opts...),
		Files:       files.NewClient(opts...),
		Media:       media.NewClient(opts...),
		Tasks:       tasks.NewClient(opts...),
		Signatures:  signatures.NewClient(opts...),
	}
}
